config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  resources :movies

  devise_for :users
  
  
  
  resources :movies, only: [:index, :show, :create, :destroy] do
    resources :reviews, except: [:index, :new, :show], shallow: true
  end
  
  get 'search' => 'movies#search' # search_path => /search
  get 'details/:imdb_id' => 'movies#details', as: 'details' # details_path(:id) => /details/:id
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :reviews, dependent: :destroy

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_and_belongs_to_many :movies
  before_destroy {movies.clear} #clears out movies from join table
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :authenticate_user!
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:show, :destroy]
  
  def index
    if params[:search]
      @movies = current_user.movies.where("title ILIKE?", "%#{params[:search]}%")
    else
      @movies = current_user.movies
    end
  end

  def create
    @movies = Movie.all
    if @movies.map(&:imdb_id).include?(movie_params[:imdb_id])
      @movie = Movie.find_by(imdb_id: movie_params[:imdb_id])
      @movie.users << current_user
      flash[:notice] = "#{@movie.title} successfully favorited."
      redirect_to @movie
    else
      @movie = current_user.movies.build(movie_params)
      if current_user.save
        flash[:notice] = "#{@movie.title} successfully favorited."
        redirect_to @movie
      else
        flash[:alert] = "Unable to favorite movie."
        redirect_to root_path
      end
    end
  end
  
  def search
  	base_url = 'http://www.omdbapi.com/?s='
  	search_term = params[:q]
  	end_point = base_url + search_term

  	response = RestClient.get(end_point)
  	data = JSON.parse(response.body)

  	@movies = data["Search"]
  	if @movies
  		render :search
  	else
  		flash[:alert] = "Sorry, your search came back empty, please try again."
			redirect_to root_path
		end
  end
  
  def details
    @movie = Movie.new
  	imdb_id = params[:imdb_id]
  	base_url = "http://www.omdbapi.com/?i="
  	end_point = base_url + imdb_id + '&plot=full'

  	response = RestClient.get(end_point)

  	@movie_info = JSON.parse(response.body)
  end

  def show
    # find_movie being run before_action
    @review = Review.new
  end

  def destroy
    # find_movie being run before_action
    current_user.movies.delete(@movie)
    flash[:alert] = "Movie successfully deleted!"
    redirect_to movies_path
  end

  private
    def find_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
        params.require(:movie).permit(:title, :year, :plot, :imdb_id, :poster)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
      before_action :find_review, only: [:edit, :update, :destroy]

  def create
  	@movie = Movie.find(params[:movie_id])
  	@review = @movie.reviews.build(review_params)
  	@review.user = current_user
  	if @movie.save
  		flash[:notice] = "Review added successfully."
  		redirect_to @movie
  	else
  		flash[:alert] = "Review could not be added, please try again."
  		redirect_to @movie
  	end
  end

  def edit
  	if @review.user != current_user
  	    not_correct_user
  	end
  end

  def update
  	if @review.user == current_user
  		if @review.update(review_params)
  			flash[:notice] = "Review updated successfully."
  			redirect_to @review.movie
  		else
  			flash[:alert] = "Unable to update review."
  			render :edit
  		end
  	else
  	    not_correct_user
  	end

  end

  def destroy
  	@movie = @review.movie
  	if @review.user == current_user
  		@review.destroy
  		flash[:alert] = "Review deleted successfully."
  		redirect_to @movie
  	else
  	    not_correct_user
  	end
  end

  private
  	def find_review
  		@review = Review.find(params[:id])
  	end

    def not_correct_user
        flash[:alert] = "You don't have permission to edit this review."
  		sign_out current_user
  		redirect_to root_path
  	end 
        

  	def review_params
  		params.require(:review).permit(:body)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'IMDB App', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to 'Favorites', movies_path %></li>
        <% end %>
      <% if user_signed_in? %>
        <li><%= link_to current_user.username.capitalize, edit_user_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
      <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('/img/home-bg.jpg')">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <div class="site-heading">
          <h1>Movie App</h1>
          <hr class="small">
          <span class="subheading">Search for your favorite movies!</span>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_notices.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imdb App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= render 'layouts/header' %>

    <div class="container">
     <%= render 'layouts/notices' %>
    <%= yield %>
    </div>

</body>
</html>

app/views/movies/details.html.erb
<h1><%= @movie_info["Title"] %></h1>
<p><%= image_tag @movie_info["Poster"], id: 'movie_poster' %></p>
<p>Year: <%= @movie_info["Year"] %></p>
<p><%= @movie_info["Plot"] %></p>

<%= simple_form_for(@movie) do |f| %>
	<%= f.hidden_field :title, :value => @movie_info["Title"] %>
	<%= f.hidden_field :year, :value => @movie_info["Year"] %>
	<%= f.hidden_field :plot, :value => @movie_info["Plot"] %>
	<%= f.hidden_field :imdb_id, :value => @movie_info["imdbID"] %>
	<%= f.hidden_field :poster, :value => @movie_info["Poster"] %>
	<%= f.button :submit, 'Favorite' %>
<% end %>

<%= link_to 'Back', :back %>

app/views/movies/index.html.erb
<div class="row">
	<div class="col-md-12">
		<h1>My Favorite Movies</h1>
	</div>
</div>
<div class="row">
	<%= form_tag(movies_path, method: "get", class: "navbar-form navbar-left") do %>
	  <div class="form-group col-md-8 floating-label-form-group controls">
  	  <%= text_field_tag :search, nil, placeholder: 'Search favorites', class: 'form-control' %>
	  </div>
	  <div class="col-md-4">
		  <%= submit_tag("Search", class: 'btn btn-default') %>
	  </div>
	<% end %>	
	<hr>
</div>
<div class="row">
<% @movies.each do |movie| %>
	<div class="col-md-4 text-center">
		<div class="thumbnail">
			<%= link_to movie do %>
		    <% if movie.poster == "N/A" %>
		    	<%= image_tag '400.jpeg', width: '150px' %><br>
		    <% else %>
		      <%= image_tag movie.poster, width: '150px' %><br>
		    <% end %>
	    <% end %>
			<div class="caption">
		    <h3><%= movie.title %></h3>
		    <%= movie.year %><br>
			  <%= link_to 'Delete', movie,
							      method: :delete, data: {confirm: 'Are you sure?'} %>
			</div>
		</div>
	</div>  
<% end %>
</div>

app/views/movies/search.html.erb
<%= render 'welcome/search' %>

<h1>Results</h1>
<div class="row">
<% @movies.each do |movie| %>
	<div class="col-md-4 text-center">
		<div class="thumbnail">
			<%= link_to details_path(movie["imdbID"]) do %>
	    	<%= image_tag movie["Poster"], width: '150px' %><br>
	    	<% end %>
			<div class="caption">
		    <h3><%= movie["Title"] %></h3>
		    <%= movie["Year"] %><br>
		    <%= link_to 'Details', details_path(movie["imdbID"]) %>
			</div>
		</div>
	</div>  
<% end %>
</div>

app/views/movies/show.html.erb
<div class="row">
    <div class="col-md-8">
        <h1><%= @movie.title %></h1>
        <p><strong>Year</strong>: <%= @movie.year %></p>
        <p><strong>Plot</strong>: <%= @movie.plot %></p>
        <%= image_tag @movie.poster, id: 'movie_poster' %>
        <% if !@movie.reviews.map(&:user_id).include?(current_user.id) %>
       
        <% end %>
        <%= link_to 'Back', :back %> 
    </div>
    <div class="col-md-4">
    	<h1>Reviews:</h1>
    	<% @movie.reviews.each do |review| %>
                <% if review.user == current_user %>
    	    <%= link_to edit_review_path review do %>
    	    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
    	    <% end %>
    	    <%= link_to review, method: :delete, data: { confirm: 'Are you sure?' } do %>
    	    <i class="fa fa-trash" aria-hidden="true"></i>
                <% end %>	
                <% end %>
                <strong><%= review.user.email %></strong>: <%= review.body %>
    	    <hr>
        <% end %>
         <%= render 'reviews/form' %>
    </div>
</div>

app/views/reviews/_form.html.erb
<h1>Add Review:</h1>
<%= simple_form_for([@movie, @review], html: { class: 'form-inline' }) do |f| %>
  <p>
    <%= f.input :body, label: false %>
  </p>
  <p>
    <%= f.button :submit, class: 'btn btn-primary' %>
  </p>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>
<%= render 'form' %>

app/views/welcome/_search.html.erb
<%= form_tag(search_path, method: "get") do %>
	<div class="form-group col-md-8 floating-label-form-group controls">
		<%= text_field_tag :q, nil, placeholder: 'Search', class: 'form-control' %>
	</div>
	<div class="col-md-4">
		<%= submit_tag("Search", class: 'btn btn-default') %>
	</div>
<% end %>

app/views/welcome/index.html.erb
<div class="row control-group">
<% if user_signed_in? %>
	<h1>Welcome, search for a movie!</h1>

	<%= form_tag(search_path, method: "get") do %>
	  <div class="form-group col-md-8 floating-label-form-group controls">
  	  <%= text_field_tag :q, nil, placeholder: 'Search', class: 'form-control' %>
	  </div>
	  <div class="col-md-4">
		  <%= submit_tag("Search", class: 'btn btn-default') %>
	  </div>
	<% end %>
<% else %>
	<h1>Welcome to the IMDB App!</h1>
<% end %>
</div>